# Generated by Django 4.0 on 2022-01-07 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 12, 2, 20, 203437), verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 12, 2, 20, 205564)),
        ),
    ]
