# Generated by Django 4.0 on 2022-01-07 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_customer_birthday_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 12, 31, 7, 988101), verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 12, 31, 7, 988911)),
        ),
    ]
