# Generated by Django 4.0 on 2022-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_category_desc_alter_customer_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
